### ISSUE TITLE
Underline URLs

### ISSUE THREAD

**Issue by Minoru** [Minoru/blog.debiania.in.ua#37]
The current theme disables underlining, but the colour we use doesn't contrast enough with the body colour; as a result, links blend in with the text.

What we could do instead is something that gatesnotes.com does:

```css
.articleContent a {
	border-bottom: 1px solid #A6DCF3;
	box-shadow: inset 0 -6px 0 #A6DCF3;
	color: inherit;
	-webkit-transition: background .15s cubic-bezier(0.33,0.66,0.66,1);
	transition: background .15s cubic-bezier(0.33,0.66,0.66,1);
}
```

A fat, mildly blue underline is highly visible yet not distracting. It's also easily distinguishable from ordinary underlining, which makes it more accessible for people with bad vision.
